version: '3.8'

services:
  btc-trading-bot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/trading/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Opcional: Redis para cache (se necessário no futuro)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

  # Opcional: PostgreSQL para dados persistentes (se necessário no futuro)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: trading_bot
  #     POSTGRES_USER: trading
  #     POSTGRES_PASSWORD: trading123
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:

